#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+TITLE: Dean's Blog
#+AUTHOR: Dean Seo (deaniac.seo@gmail.com)
#+DATE:  <2020-01-25 Sat 14:22>
#+options: timestamp:nil

* Table of Contents
.

* What's Transaction Limiter?
A Transaction Limiter helps ensure you don't accidentally send more orders than you're allowed to.

* Why do we need Transaction Limiter?
To maintain a fair trading environment and protect individual traders, global exchanges often limit the total number of order requests a market participant can send, within a fixed time frame.
It is never a good idea to break this rule, because there will be +punishment+ consequences.
For example, the first offense might result in a trading suspension for a few hours.
If the behavior continues, you could face a longer ban - three months, six months, or even permanently.

Don't get me wrong. These rules are essential.
It's a good idea to ban those who can't keep their trading system under control. This is for everyone and to maintain fairness in the market.

** Crypto Trading and Transaction Limiter
Crypto exchanges often impose even stricter restrictions.

Since [[https://en.wikipedia.org/wiki/Bankruptcy_of_FTX][the fall of FTX]], which supported the [[https://en.wikipedia.org/wiki/Financial_Information_eXchange#Technical_specifications][FIX protocol]], most users trade, using the exchange's WebAPIs where the definition of the transaction limit is somewhat /vague/
so that they're advised to make order requests in a more /conservative/ stance.

* How to develop Transaction Limiter?
#+begin_note
In my opinion, creating a transaction limiter class is a fascinating project, not just for the trading industry but in general.
You can design the implementation to be flexible enough to meet your own business requirements, such that you can control how many times certain tasks can be executed.
#+end_note

To keep things simple, we'll focus on the most essential requirements:

- *Check* if we have capacity.
- *Decrement* capacity by 1 if we do.

We'll define two interfaces, =check()= and =decrement()=.
Although there can be various ways, I'll use a "circular buffer" in this article.

Now, imagine a scenario where we must send orders regardless of the limiter, such as when we need to send cancellation orders due to a sudden price move or our hedging position becoming neutral.
To handle this edge case, we'll also create an exclusive buffer which accepts orders even when we hit the transaction limit.

** Implement a base class
A base class defines those two interfaces as well as =priority_tag=.

The *priority tag* covers the above-mentioned case where we must send cancel orders, which means we'll always have to keep a small room for urgent cancellations.

Note that I made the base class have this "optional" priority tag so the users can decide if the order carries urgency in it.
When an order is just a new FOK order, for example, probably there's no need to use the tagged overload.
#+BEGIN_SRC C++ :includes <iostream> :flags -std=c++20 :results silent raw :exports both :main no :noweb yes
  enum class priority_tag { Tag_ };

  template <typename ImplType>
  struct base_limitter {
      auto *This() { return static_cast<ImplType *>(this); }
      auto *This() const { return static_cast<const ImplType *>(this); }

      [[nodiscard]] constexpr auto size() const noexcept { return This()->size(); }

      bool check_capacity_and_add() { return This()->check_capacity_and_add(); }
      bool check_capacity_and_add(priority_tag) {
          if constexpr (requires(ImplType impl, priority_tag tag) {
                            { impl.check_capacity_and_add(tag) } -> std::same_as<bool>;
                        }) {
              return This()->check_capacity_and_add(priority_tag{});
          } else {
              // The implementation doesn't support "prioritiness".
              return This()->check_capacity_and_add();
          }
      }
  };
#+END_SRC

An limiter implementation inheriting from =base_limitter= might not support /prioritiness/.
In that case, =priority_tag= will be ignored, and the regular overload will be chosen.

** Implement a Circular Buffer
A [[file:circular-buffer.org][circular buffer]] is probably a data structure candidate a *Transaction Limiter* needs to use. (/For obvious reasons, you shouldn't use my implementation in production/.)
There are many solid implementations of circular buffer available, including [[https://www.boost.org/doc/libs/1_79_0/doc/html/circular_buffer.html][boost::circular_buffer]].

* Conclusion
.

















