#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+TITLE: When are we using a sequencially consistent total ordering?
#+AUTHOR: Dean Seo (deaniac.seo@gmail.com)
#+DATE:  [2020-05-25 월]
#+HTML_HEAD: <style> #content{max-width:900px;}</style>>
#+OPTIONS: timestamp:nil
#+OPTIONS: num:nil

* Table of Contents
.

* When are we using total ordering?
Since C++11, C++ has covered memory models in the standard:
- =std::memory_order_relaxed=
- =std::memory_order_consume=
- =std::memory_order_acquire=
- =std::memory_order_release=
- =std::memory_order_acq_rel=
- =std::memory_order_seq_cst=

For obvious reasons the committes did the hard work to cover different platforms' memory model to allow us
to write a portable program within C++.

This is a delicate subject underlying [[https://www.kernel.org/doc/Documentation/memory-barriers.txt][how the Linux kernel's supports the atomic operations]].
In x86, a strongly ordered architecture, however this model can be simpler though.

** =std::memory_order_consume=
This implies the /address-dependency partial load barrier./
It ins't always obvious to identify the address-dependant loads.

The good news is that in strongly ordered architectures, this is now a /historical/ concern, automatically implied in a load barrier today.
=std::memory_order_consume= is likely to be only used to prevent compiler reorderings within C++'s memory model.

** =std::memory_order_relaxed=
Since x86 doesn't support a relaxed load and store in the hardware level, our concern narrows down to the compiler optimization where we make sure of a valid release/acquire /synchronize-with/ relation.
In general, a strong lock instrucion like a =lock= prefix or =xchg= isn't emitted for a rel/acq operation by the compiler.

** =std::memory_order_release= / =std::memory_order_acquire=
In most cases this pair is what we want to use.

Each operation is a specific partial ordering for a store and load pair.
In the C++ standard, they must be paired from each thread to be visible to the counterpart thread without the modification order affected.

** =std::memory_order_seq_cst=
This implies a total ordering, which is the strongest, full memory barrier you can use.
In this post, I'm gonna talk about a situation that a /rel/acq/ pair isn't good enough, whilst =std::memory_order_seq_cst= must be present. (todo: remove: in a 3rd party library, maybe 'must').

* Memory reordering caught in the act
[[https://preshing.com/20120515/memory-reordering-caught-in-the-act][Preshing's post]] about demonstrating memory reordering done in x86 shows that a strongly-ordered CPU isn't completley immunne to the modification order [[http://preshing.com/files/ordering.zip][being reordred]].
Here's the equivalent version where I only replaced his [[https://en.wikipedia.org/wiki/Mersenne_Twister][Mersenne Twister]] implemetation with =std::mt19337=:
#+BEGIN_SRC C++ :exports both :main no :noweb yes
  #define USE_CPU_FENCE 0

  sem_t beginSema1;
  sem_t beginSema2;
  sem_t endSema;

  int X, Y;
  int r1, r2;
  std::random_device seed_generator;

  void *thread1Func(void *param) {
      std::mt19937 random(seed_generator());
      for (;;) {
          sem_wait(&beginSema1);  // Wait for signal
          while (random() % 8 != 0) {}  // Random delay

          // ----- THE TRANSACTION! -----
          X = 1;
  #if USE_CPU_FENCE
          std::atomic_thread_fence(std::memory_order_seq_cst);
  #else
          std::atomic_signal_fence(std::memory_order_seq_cst); // Would it work?
          // asm volatile("" ::: "memory");  // Prevent compiler reordering
  #endif
          r1 = Y;

          sem_post(&endSema);  // Notify transaction complete
      }
    
      return nullptr;  // Never returns
  };

  void *thread2Func(void *param) {
      std::mt19937 random(seed_generator());
      for (;;) {
          sem_wait(&beginSema2);  // Wait for signal
          while (random() % 8 != 0) {}  // Random delay

          // ----- THE TRANSACTION! -----
          Y = 1;
  #if USE_CPU_FENCE
          std::atomic_thread_fence(std::memory_order_seq_cst);
  #else
          std::atomic_signal_fence(std::memory_order_seq_cst); // Would it work?
          // asm volatile("" ::: "memory");  // Prevent compiler reordering
  #endif
          r2 = X;

          sem_post(&endSema);  // Notify transaction complete
      }
    
      return nullptr;  // Never returns
  };

  int main() {
      // Initialize the semaphores
      sem_init(&beginSema1, 0, 0);
      sem_init(&beginSema2, 0, 0);
      sem_init(&endSema, 0, 0);

      // Spawn the threads
      pthread_t thread1, thread2;
      pthread_create(&thread1, nullptr, thread1Func, nullptr);
      pthread_create(&thread2, nullptr, thread2Func, nullptr);

      // Repeat the experiment ad infinitum
      std::size_t detected = 0;
      for (int iterations = 1; ; iterations++)
      {
          // Reset X and Y
          X = 0;
          Y = 0;

          // Signal both threads
          sem_post(&beginSema1);
          sem_post(&beginSema2);

          // Wait for both threads
          sem_wait(&endSema);
          sem_wait(&endSema);

          // Check if there was a simultaneous reorder
          if (r1 == 0 and r2 == 0)
          {
              detected++;
              printf("%d reorders detected after %d iterations\n", detected, iterations);
          }
      }

      return 0;  // Never returns
  }
#+END_SRC

To be logically consistent, given that each operation is atomic:
#+begin_example
  +------+------+------+------------------+
  | case | T1   | T2   | Misc.            |
  |------+------+------+------------------|
  | #1   | X=1  |      |                  |
  |      | r1=Y |      |                  |
  |      |      | Y=1  |                  |
  |      |      | r2=X |                  |
  |------+------+------+------------------|
  | #2   | X=1  |      |                  |
  |      |      | Y=1  |                  |
  |      | r1=Y |      |                  |
  |      |      | r2=X |                  |
  |------+------+------+------------------|
  | #3   |      | Y=1  |                  |
  |      | X=1  |      |                  |
  |      | r1=Y |      |                  |
  |      |      | r2=X |                  |
  |------+------+------+------------------|
  | #4   | X=1  | Y=1  | at the same time |
  |      | r1=Y | r2=X | at the same time |
  |------+------+------+------------------|
  | #5   | X=1  | Y=1  | at the same time |
  |      | r1=Y |      |                  |
  |      |      | r2=X |                  |
  |------+------+------+------------------|
  | #6   | X=1  | Y=1  | at the same time |
  |      |      | r2=X |                  |
  |      | r1=Y |      |                  |
  +------+------+------+------------------+
#+end_example

you can tell that "r0 = r1 = 0" is impossible.
The reason you're seeing the reordering is possibly each cache visibe to differnt cpus isn't /synchronized-with/, as follows:
#+begin_src text
                  +------+                +-------+                                                
                  | X=0  |                | X=0   |                              
  +-------+       +------+                +-------+       +-------+             
  | CPU1  |       | Y=0  |                | Y=0   |       | CPU2  |     
  |       |       +------+                +-------+       |       |     
  |       |       :      :           -----| Y=1   |       |       |     
  |       |       :      :          /     +-------+       |       |     
  |       |       :      :         /      | r2=X  |------>| r2=0  |     
  |       |       +------+        |       +-------+       |       |     
  |       |------>| X=1  |---     |       :       :       |       |     
  |       |       +------+   \    |       :       :       |       |                    
  |       |       :      :    \   |       +-------+       |       |
  |       |       :      :     ---------->| X=1   |------>| miss! |
  |       |       :      :        |       +-------+       |       |
  |       |       :      :        |       :       :       |       |
  |       |       +------+        |       :       :       |       |
  | r1=0  |<------| r1=Y |        |       :       :       |       |
  |       |       +------+        |       :       :       |       |
  |       |       :      :       /        :       :       |       |
  |       |       +------+      /         :       :       |       |
  | miss! |<------| Y=1  |<----           :       :       |       |
  |       |       +------+                :       :       |       |
  |       |       :      :                :       :       |       |
  +-------+       :      :                :       :       +-------+
#+end_src

As you see, it is totally allowed that a modification in one thread isn't visible to others immediately.
To prevent that happening, it's essential to impose the sequencially consistent full ordering such as =mfence= in the original post so the single ordering is visible to all CPUs.

* Isn't a rel/acq pair good enough to prevent reordering?
A release and acquire must be paired and when paired there's a guaranteed ordering such that any atomic opreations
before the release /happens-before/ any atomic operations.

The C++'s memory model essentially provides the same definition. When paired, the 'acquire-er' is guaranteed to have the same ordering.
Thus, the good ole =is_ready= practice in C is now available in C++, as follows:
#+BEGIN_SRC C++ :includes <memory> :flags -std=c++20 :results silent raw :exports both :main no :noweb yes
  std::atomic<int> value;
  std::atomic<bool> is_ready;

  void release() {
      value.store(1, std::memory_order_relaxed);
      is_ready.store(true, std::memory_order_release);
  }

  auto acquire() {
      if (const auto readiness = is_ready.load(std::memory_order_acquire);
          readiness) {
          return value.load(std::memory_order_relaxed);
      }

      return 0;
  }
#+END_SRC

That's it. In fact, for most cases in atomic programming, a /rel-acq/ fair is good enough. There's a bonus in x86.
Considering it's strongly ordered by default there's no strong instrucution yield such as =lock= prefix or =mfence=.

So I once wondered, "_what's a use case for =std::memory_order_seq_cst=?_"

* Placing general barriers for a total ordering
In short, you use =std::memory_order_seq_cst= for full ordering that covers operations beyond the rel-acq chain.
In a well-designed structure, probably it's best to avoid placing total orderings often, but in some cases that might be inevitable.

Recycling Preshing's code above, let's add one more thread off the rel/acq partial ordering chain:
#+BEGIN_SRC C++ :includes <atomic> <random> :flags -std=c++20 :results silent raw :exports both :main no :noweb yes

#+END_SRC











