#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+TITLE: Draft Title
#+AUTHOR: Dean Seo (deaniac.seo@gmail.com)
#+DATE:  [2023-05-25 Thu]
#+HTML_HEAD: <style> #content{max-width:900px;}</style>>
#+OPTIONS: timestamp:nil
#+OPTIONS: num:nil

* Table of Contents
.

* When are we using total ordering?
Since C++11, C++ has covered memory models in the standard:
- std::memory_order_relaxed
- std::memory_order_consume
- std::memory_order_acquire
- std::memory_order_release
- std::memory_order_acq_rel
- std::memory_order_seq_cst

For obvious reasons the committes did the hard work to cover different platforms' memory model to allow us
to write a portable program within C++.

This is a delicate subject underlying [[https://www.kernel.org/doc/Documentation/memory-barriers.txt][how the Linux kernel's supports the atomic operations]].
In x86, a strongly ordered architecture, however this model can be simpler though.

** std::memory_order_consume
This implies the /address-dependency partial load barrier./
It ins't always obvious to identify the address-dependant loads.

The good news is that in strongly ordered architectures, this is now a /historical/ concern, automatically implied in a load barrier today.
=std::memory_order_consume= is likely to be only used to prevent compiler reorderings within C++'s memory model.

** std::memory_order_relaxed
Since x86 doesn't support a relaxed load and store in the hardware level, our concern narrows down to the compiler optimization where we make sure of a valid release/acquire /synchronize-with/ relation.
In general, a strong lock instrucion like a =lock= prefix or =xchg= isn't emitted for a rel/acq operation by the compiler.

** std::memory_order_release / std::memory_order_acquire
In most cases this pair is what we want to use.

Each operation is a specific partial ordering for a store and load pair.
In the C++ standard, they must be paired from each thread to be visible to the counterpart thread without the modification order affected.

** std::memory_order_seq_cst
This implies a total ordering, which is the strongest, full memory barrier you can use.
In this post, I'm gonna talk about a situation that a /rel/acq/ pair isn't good enough, whilst =std::memory_order_seq_cst= must be present. (todo: remove: in a 3rd party library, maybe 'must').

* Memory reordering caught in the act
[[https://preshing.com/20120515/memory-reordering-caught-in-the-act/][Preshing's post]] about demonstrating memory reordering done in x86 shows that a strongly-ordered CPU isn't completley immunne to the modification order [[http://preshing.com/files/ordering.zip][being reordred]].
Here's the equivalent version where I only replaced his [[https://en.wikipedia.org/wiki/Mersenne_Twister][Mersenne Twister]] implemetation with =std::mt19337=:
#+BEGIN_SRC C++ :includes <cstdio> <random> <thread> <atomic> <pthread.h> <semaphore.h> :flags -std=c++20 :results silent raw :exports both :main no :noweb yes
  #define USE_CPU_FENCE 0

  sem_t beginSema1;
  sem_t beginSema2;
  sem_t endSema;

  int X, Y;
  int r1, r2;
  std::random_device seed_generator;

  void *thread1Func(void *param) {
      std::mt19937 random(seed_generator());
      for (;;) {
          sem_wait(&beginSema1);  // Wait for signal
          while (random() % 8 != 0) {}  // Random delay

          // ----- THE TRANSACTION! -----
          X = 1;
  #if USE_CPU_FENCE
          std::atomic_thread_fence(std::memory_order_seq_cst);
  #else
          std::atomic_signal_fence(std::memory_order_seq_cst); // Would it work?
          // asm volatile("" ::: "memory");  // Prevent compiler reordering
  #endif
          r1 = Y;

          sem_post(&endSema);  // Notify transaction complete
      }
    
      return nullptr;  // Never returns
  };

  void *thread2Func(void *param) {
      std::mt19937 random(seed_generator());
      for (;;) {
          sem_wait(&beginSema2);  // Wait for signal
          while (random() % 8 != 0) {}  // Random delay

          // ----- THE TRANSACTION! -----
          Y = 1;
  #if USE_CPU_FENCE
          std::atomic_thread_fence(std::memory_order_seq_cst);
  #else
          std::atomic_signal_fence(std::memory_order_seq_cst); // Would it work?
          // asm volatile("" ::: "memory");  // Prevent compiler reordering
  #endif
          r2 = X;

          sem_post(&endSema);  // Notify transaction complete
      }
    
      return nullptr;  // Never returns
  };

  int main() {
      // Initialize the semaphores
      sem_init(&beginSema1, 0, 0);
      sem_init(&beginSema2, 0, 0);
      sem_init(&endSema, 0, 0);

      // Spawn the threads
      pthread_t thread1, thread2;
      pthread_create(&thread1, nullptr, thread1Func, nullptr);
      pthread_create(&thread2, nullptr, thread2Func, nullptr);

      // Repeat the experiment ad infinitum
      std::size_t detected = 0;
      for (int iterations = 1; ; iterations++)
      {
          // Reset X and Y
          X = 0;
          Y = 0;

          // Signal both threads
          sem_post(&beginSema1);
          sem_post(&beginSema2);

          // Wait for both threads
          sem_wait(&endSema);
          sem_wait(&endSema);

          // Check if there was a simultaneous reorder
          if (r1 == 0 and r2 == 0)
          {
              detected++;
              printf("%d reorders detected after %d iterations\n", detected, iterations);
          }
      }

      return 0;  // Never returns
  }
#+END_SRC

To be logically consistent, "r0 = r1 = 0" is impossible as follows:
| case | T1 | T2 |
|------+----+----|
|      |    |    |
|      |    |    |
|      |    |    |
|      |    |    |
|      |    |    |
|      |    |    |
|      |    |    |
|      |    |    |
|      |    |    |
|      |    |    |
|      |    |    |
|      |    |    |
|      |    |    |
|      |    |    |

In case r0 = r1 = 1 this is the diagram:
#+begin_example

#+end_example


