#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+TITLE: Painkillers and NSAIDs
#+AUTHOR: Dean Seo (deaniac.seo@gmail.com)
#+DATE:  [2019-09-28 토]
#+options: timestamp:nil

* Table of Contents
.

* Painkillers and NSAIDs
Are Painkiller /bad/? I grew up hearing painkilers merely /tricks/ my brain to delusionally believe you aren't hurt.
According to them, it doesn't heal the pain, but just /hides/ it.

I still see people inclined to avoid taking the painkillers because of the very reason, ending up visiting those alternative doctors with a hope
that they might have a 'proper' method to ease their pain.

Back in Korea those TCM doctors (though they don't like to call them that - we pioneered a new term "*Doctors of Korean Medicine*") knowingly
pulled the wool over the eyes.

I guess, regardless of whether it's true, this sounds convincing enough indeed.

But really, is that really true?
We have so many different kinds of medicines labeled a painkiller.

- Is every single one of them designed that way?
- Is the family doctor in your neighbor just prescribing a blue pill?

To answer that question, we need to define what really a painkiller is.




** What are painkillers?
.

** NSAIDs
.

*** 타이레놀은?
.

* Conclusion
TL;DR, most painkilers actually do help you heal the root cause of your pain so it's probably a wrong judgement to avoid taking them when prescribed by a doctor,
although there are some kinds that are designed to only reduce the level of pain by faking your brain.


